[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/themes/tmux-everforest"]
    type = "git-repo"
    url = "https://github.com/jthxdev/tmux-everforest.git"
[".tmux/plugins/catppuccin/tmux"]
    type = "git-repo"
    url = "https://github.com/catppuccin/tmux.git"
[".tmux/plugins/tmux-battery"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-battery.git"
[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme.git"
[".phpenv"]
    type = "git-repo"
    url = "https://github.com/phpenv/phpenv.git"
[".phpenv/plugins/php-build"]
    type = "git-repo"
    url = "https://github.com/php-build/php-build.git"
[".tmux/plugins/tmux-continuum"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-contimuum.git"
[".tmux/plugins/tmux-resurrect"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-resurrect.git"
[".tmux/plugins/tmux-cpu"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-cpu.git"
["displaylink-debian"]
    type = "git-repo"
    url = "https://github.com/AdnanHodzic/displaylink-debian.git"
[".tmux/plugins/tpm"]
    type="git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
["wiki"]
    type = "git-repo"
    url = "git@github.com:koltempleister/wiki.git"

